### ISSUE TITLE
Compiling Numba code fails on 16.04

### ISSUE THREAD

**Issue by themightyoarfish** [danielhanchen/hyperlearn#16]
At the end of `python setup.py install`, it says to run
```
#### If you want to compile Numba code, please run:
    >>>>   python numba_compile.py
```
to compile Numba. Doing this gives me
```
Progress: |||||||||||||||Traceback (most recent call last):
  File "numba_compile.py", line 6, in <module>
    from hyperlearn.numba.funcs import *
  File "/home/share/software/sources/hyperlearn/hyperlearn/numba/funcs.py", line 4, in <module>
    from ..cfuncs import uinteger
  File "/home/share/software/sources/hyperlearn/hyperlearn/cfuncs.py", line 3, in <module>
    from .cython.base import isComplex, available_memory, isList
ModuleNotFoundError: No module named 'hyperlearn.cython.base'
```

**Comment by danielhanchen** [comment]
Ye also same problem. Still fixing it! Sorry!
